---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: preview
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: ca-cluster-issuer
    tweetch.home.arpa/name: preview-tweetch
    tweetch.home.arpa/url: https://preview.tweetch.home.arpa
    tweetch.home.arpa/icon: wrench
spec:
  rules:
  - host: preview.tweetch.home.arpa
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: browser-sync
            port:
              number: 3000
      - path: /browser-sync/socket.io
        # pathType: ImplementationSpecific # Does not trigger warning
        pathType: Prefix
        backend:
          service:
            name: browser-sync
            port:
              number: 443
  tls:
  - hosts:
    - preview.tweetch.home.arpa
    secretName: preview-cert
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: browser-sync
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: ca-cluster-issuer
    tweetch.home.arpa/name: browser-sync-tweetch
    tweetch.home.arpa/url: https://browser-sync.tweetch.home.arpa
    tweetch.home.arpa/icon: wrench
spec:
  rules:
  - host: browser-sync.tweetch.home.arpa
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: browser-sync
            port:
              number: 3001
      - path: /browser-sync
        pathType: Prefix
        backend:
          service:
            name: browser-sync
            port:
              number: 443
  tls:
  - hosts:
    - browser-sync.tweetch.home.arpa
    secretName: browser-sync-cert
