---
apiVersion: gateway.networking.k8s.io/v1
kind: ListenerSet
metadata:
  name: browser-sync
  annotations:
    cert-manager.io/cluster-issuer: ca-cluster-issuer
spec:
  parentRef:
    namespace: cilium
    name: cilium
    kind: Gateway
    group: gateway.networking.k8s.io
  listeners:
  - name: preview
    hostname: preview.tweetch.home.arpa
    protocol: HTTPS
    port: 443
    tls:
      mode: Terminate
      certificateRefs:
      - kind: Secret
        group: ""
        name: preview-tweetch-cert
  - name: browser-sync
    hostname: browser-sync.tweetch.home.arpa
    protocol: HTTPS
    port: 443
    tls:
      mode: Terminate
      certificateRefs:
      - kind: Secret
        group: ""
        name: browser-sync-tweetch-cert
