---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: tweetch
spec:
  hostnames:
  - tweetch.cluster.local
  parentRefs:
  - name: tweetch
    kind: ListenerSet
    group: gateway.networking.k8s.io
    sectionName: tweetch
  rules:
  - backendRefs:
    - name: tweetch
      port: 80
    matches:
    - path:
        type: PathPrefix
        value: /
