---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: tweetch
spec:
  template:
    spec:
      containers:
        - name: tweetch
          image: shokohsc/tweetch
          env:
            - name: ENV
              value: development
            - name: USE_SENTRY
              value: "true"
            - name: SENTRY_DSN
              value: https://2f15ffed2e254ced911e78de9312afe0\@glitchtip.shokohsc.home/1
            - name: TWITCH_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: tweetch
                  key: client-id
            - name: TWITCH_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: tweetch
                  key: client-secret
          resources:
            requests:
              cpu: 10m
              memory: 64M
            limits:
              cpu: 1000m
              memory: 256M
