apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev-tweetch
resources:
  - browser-sync/
bases:
  - ../../base
patchesStrategicMerge:
  - http-route.yaml
  - listener-set.yaml
  - deployment.yaml
