apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev-tweetch
resources:
  - browser-sync/
  - secret.yaml
bases:
  - ../../base
patchesStrategicMerge:
  - ingress.yaml
  - deployment.yaml
